name: Schedule API Call

on:
  schedule:
    - cron: '*/1 * * * *'  # This will run every minute

jobs:
  callApi:
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel API
        run: curl -X GET "https://pne-coaster-wheel-adjustments.vercel.app/api/update-sheet"
